language: android
jdk:
  - oraclejdk8
android:
  components:
   - tools
   - build-tools-27.0.1

   - android-27

before_install:
  - yes | sdkmanager "platforms;android-27"
script: ./gradlew -Dorg.gradle.jvmargs=-Xmx1536m assembleDebug lintDebug testDebugUnitTest

licences:
  - '.+'